export default function ReserveHead() {
  return (
    <>
      <title>Reserve at Meadow Kitchen (Toronto) | OpenTable</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
